### PR TITLE
MidProject Check

### PR DESCRIPTION
**Pull request by kejin-qian**
Please check the following _MidProject Check Items_:

1. acquire_data.py (https://github.com/kejin-qian/Malicious-URL-Classifier/blob/midproject/src/acquire_data.py) 

This python script contains functions: 
    - download source data from 3 different websites and save them to local.
    - make a final dataset for this project using these three large datasets.

2. download_file.py (https://github.com/kejin-qian/Malicious-URL-Classifier/blob/midproject/src/download_file.py)

This python script is used to download files from S3 bucket to local.

3. upload_file.py (https://github.com/kejin-qian/Malicious-URL-Classifier/blob/midproject/src/upload_file.py)

This python script is used to upload files from local to the S3 bucket.

4. create_database.py (https://github.com/kejin-qian/Malicious-URL-Classifier/blob/midproject/src/sql/create_database.py)

This python script will help to build classes to create the following two tables:
* Url_prediction: to store user inputs
* Url_features: to store features generated for all urls in the dataset

It also contains a create_db function to create database schema in RDS or locally by passing required argument. 

5. MidProject Deck (https://github.com/kejin-qian/Malicious-URL-Classifier/blob/midproject/Mid-project%20Review%20Deck.pdf)
 
Thank you.

Here are some instructions on how to run the python scripts in terminal: 

0. To clone my repo to your local, run

`git clone https://github.com/kejin-qian/Malicious-URL-Classifier.git`

Instructions on running scripts in terminal:

- Create a new environment by `conda create -n envName python=3.6` and activate your new environment by `conda activate envName`

- "cd" to the project  folder

- Switch to the right branch for this mid-project check
`git checkout midproject`

- run `pip install -r requirements.txt` to install all the packages needed for files submitted as mid project check.

- Now you can run the python scripts:

1. acquire_data.py 
	`python src/acquire_data.py` 
2. download_file.py
	`python src/download_file.py --path_of_object_to_download=<path to the file on S3> --bucket_name=<S3 bucket name> --output_file_path=<path to save the downloaded file>`
3. upload_file.py
	`python src/upload_file.py --input_file_path=<path to the file to be uploaded> --bucket_name=<S3 bucket name> --output_file_path=<path to where you want to store the file on S3>`
4. create_database.py 
	To create database schema on RDS: 
	`python src/sql/create_database.py --RDS=True`
	To create database schema locally in sqlite:
	`python src/sql/create_database.py --RDS=False`

### CODE REVIEW

**Comment by kejin-qian** [comment]
I noticed a path error in the acquire_data.py file by my own. The corrected version was pushed. Here is the link to it: https://github.com/kejin-qian/Malicious-URL-Classifier/blob/midproject/src/acquire_data.py

**Comment by kejin-qian** [comment]
Here are some instructions on how to run the python scripts in terminal: 

0. To clone my repo to your local, run

`git clone https://github.com/kejin-qian/Malicious-URL-Classifier.git`

Instructions on running scripts in terminal:

- Create a new environment by `conda create -n envName python=3.6` and activate your new environment by `conda activate envName`

- "cd" to the project  folder

- Switch to the right branch for this mid-project check
`git checkout midproject`

- run `pip install -r requirements.txt` to install all the packages needed for files submitted as mid project check.

- Now you can run the python scripts:

1. acquire_data.py 
	`python src/acquire_data.py` 
2. download_file.py
	`python src/download_file.py --path_of_object_to_download=<path to the file on S3> --bucket_name=<S3 bucket name> --output_file_path=<path to save the downloaded file>`
3. upload_file.py
	`python src/upload_file.py --input_file_path=<path to the file to be uploaded> --bucket_name=<S3 bucket name> --output_file_path=<path to where you want to store the file on S3>`
4. create_database.py 
	To create database schema on RDS: 
	`python src/sql/create_database.py --RDS=True`
	To create database schema locally in sqlite:
	`python src/sql/create_database.py --RDS=False`

**Comment by chuandu2** [comment]
Thank for the updates! One first thing to point out is to add instructions to clone your repo branch to users' local desktop, then use terminal to run
for example: git clone https://github.com/kejin-qian/Malicious-URL-Classifier.git <target directory name>

**Comment by chuandu2** [comment]
For creating a new environment, the instruction `conda activate <envName>` may not work for all situations, and gives the error as "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'."

Here you may need to add "if `conda activate <envName>` doesn't work, please try `source activate <envName>`"

**Comment by kejin-qian** [comment]
Thanks for the advice! The instruction of cloning my repo to local has been added. Also I put all the instructions on running my python scripts into the first chat box to make it easier to find.

**Comment by chuandu2** [comment]
Running acquire_data.py failed due to the missing module, error showed below, please refine your requirements.txt

Traceback (most recent call last):
  File "acquire_data.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by kejin-qian** [comment]
Did you run `pip install -r requirements.txt`? I'm pretty sure pandas was listed there.

https://github.com/kejin-qian/Malicious-URL-Classifier/blob/c2530459307671378d0291c7bb687bab6d750461/requirements.txt#L12

**Comment by kejin-qian** [comment]
One other possibility is that you are running the requirements.txt and python scripts from my master branch. Try `git checkout midproject` to switch to the right branch. 

Added this instruction on switching branch to my instructions above.

**Comment by chuandu2** [comment]
`acquire_data.py` worked well and successfully downloaded data from url to local as "project_data.csv"

**Comment by chuandu2** [comment]
`upload_file.py` worked well and successfully uploaded the data into the user's (my own) S3 bucket, the output is shown in the screenshot

image

**Comment by chuandu2** [comment]
Got this error when running `create_database.py`

dhcp-10-105-186-65:Malicious-URL-Classifier Sophie$ python src/sql/create_database.py --RDS=False
Traceback (most recent call last):
  File "src/sql/create_database.py", line 124, in <module>
    engine = sql.create_engine(get_engine_string(RDS=args.RDS))
  File "/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 423, in create_engine
    return strategy.create(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: 'None'

**Comment by chuandu2** [comment]
https://github.com/kejin-qian/Malicious-URL-Classifier/blob/c2530459307671378d0291c7bb687bab6d750461/src/sql/create_database.py#L133

After creating a new session and adding new data, there should be a `session.close()` in the end

**Comment by chuandu2** [comment]
`create_database.py` can run in local, and generate a new database named "url_classification.db"

image

**Comment by kejin-qian** [comment]
Fixed the error in create_database.py by adding the following if statement
https://github.com/kejin-qian/Malicious-URL-Classifier/blob/70623e690c76cc8ce35ec1d0c75b68b643d57354/src/sql/create_database.py#L125
I believe you can now create two databases both locally and in RDS by setting RDS=True/False.
Please check! Thanks!

**Comment by chuandu2** [comment]
PR Review Summary
The whole pipeline is good to go now.
- Functionality: all functions have been rerun and all work well now
- Readability & code quality: code is easy to read with clear logic and effective comments. The design decisions that were made can be understood easily. Variables and method names are meaningful, and it's clear what they are referencing. Functions are sized properly.
- Overall design: the whole pipeline was built logically from data acquirement to database construction. Yes it is modular and extensible.
- Testing: Functions can be easily testable.
- Documentation: Doc-strings and comments in code were added effectively and instructions were in detail now and easy to follow. Overall design and approach has been explained well and commit statements are clear. Changes are not sufficiently explained in the PR but was updated effectively during the review conversations.
Great work!

**Comment by kejin-qian** [comment]
README.md was updated by adding all the instructions on how to run the scripts for MidProject check.

**Pull request merged**
